// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// Document: https://firebase.google.com/docs/web/setup#access-firebase

import { FirebaseOptions, initializeApp } from 'firebase/app';

const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyDZ3NMrHT8sLqS6PIBbaUOwa9ceyMGGVkA",
  authDomain: "playnite-30409.firebaseapp.com",
  databaseURL: "https://playnite-30409-default-rtdb.firebaseio.com",
  projectId: "playnite-30409",
  storageBucket: "playnite-30409.firebasestorage.app",
  messagingSenderId: "930117680987",
  appId: "1:930117680987:web:ffb09a2738f112e470247e",
  measurementId: "G-H4LHEW1TLV"
};

function getFirebaseConfig() {
  if (!firebaseConfig || !firebaseConfig.apiKey) {
    throw new Error('No Firebase configuration object provided.' + '\n' +
      'Add your web app\'s configuration object to src/firebase/config.ts');
  } else {
    return firebaseConfig;
  }
}

export const app = initializeApp(getFirebaseConfig());
